# Generated by Django 4.1.2 on 2022-10-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0003_unit_vehicle_unit_weapon_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military.crew')),
            ],
        ),
        migrations.DeleteModel(
            name='Vechicle',
        ),
        migrations.AlterField(
            model_name='unit',
            name='vehicle',
            field=models.ManyToManyField(to='military.vehicle'),
        ),
    ]
