# Generated by Django 4.1.2 on 2022-10-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0004_vehicle_delete_vechicle_alter_unit_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='crew',
        ),
    ]
